name: Lancer les tests

on: push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python3 -mpip install pip-tools
          pip-sync api/requirements.txt api/requirements-dev.txt

      - name: Run tests
        run: |
          cd api && make test-python

      - name: Check types
        run: |
          cd api && make check

